### CREATE
POST http://localhost:8080/api/v1/buyers
Content-Type: application/json

{
  "name": "Gigel",
  "country": "Germany",
  "email": "example5@fakemail.com",
  "age": 33
}


### READ SPECIFIC
GET http://localhost:8080/api/v1/buyers


### READ SPECIFIC
GET http://localhost:8080/api/v1/buyers/7


### UPDATE SPECIFIC/CREATE
PUT http://localhost:8080/api/v1/buyers/7
Content-Type: application/json

{
  "name": null,
  "country": "Spain",
  "email": "example6@fakemail.com",
  "age": null
}


### DELETE SPECIFIC
DELETE http://localhost:8080/api/v1/buyers/6


