### CREATE
POST http://localhost:8080/api/v1/orders
Content-Type: application/json

{
  "orderNumber": "12385",
  "buyerId": 5,
  "status": 1,
  "productIds": [7 ,7]
}


### READ ALL
GET http://localhost:8080/api/v1/orders


### READ SPECIFIC
GET http://localhost:8080/api/v1/orders/11


### UPDATE SPECIFIC
PUT http://localhost:8080/api/v1/orders/7
Content-Type: application/json

{
  "productIds": [4 , 2, 3]
}


### DELETE SPECIFIC
DELETE http://localhost:8080/api/v1/orders/10
